### ISSUE TITLE
How to add more voices

### ISSUE THREAD

**Issue by CareerBuggy** [westonruter/spoken-word#8]
At present, the WordPress plugin has 2 US voices, one is male and another is female. I would like to add 2 more voices one is UK male and UK female. Let me know how I can add these voices.
Thanks

**Comment by westonruter** [comment]
The voices are part of your operating system. Here is how you install more on a Mac: https://support.apple.com/guide/mac-help/change-the-voice-your-mac-uses-to-speak-text-mchlp2290/mac
